CXX-1687 run auto encryption spec tests on evergreen

diff --git a/.mci.yml b/.mci.yml
--- a/.mci.yml
+++ b/.mci.yml
@@ -128,6 +128,12 @@ functions:
                 export MONGODB_VERSION=${mongodb_version}
                 export AUTH=${AUTH}
                 export TOPOLOGY=${TOPOLOGY|server}
+
+                echo '${workdir}'
+                touch '${workdir}'/mongodb_binaries_path.txt
+
+                echo $MONGODB_BINARIES > '${workdir}'/mongodb_binaries_path.txt
+                
                 echo "{ \"releases\": { \"default\": \"$MONGODB_BINARIES\" }}" > $MONGO_ORCHESTRATION_HOME/orchestration.config
                 ./.evergreen/run-orchestration.sh
 
@@ -239,9 +245,19 @@ functions:
                   # `test_crud_specs` and `test_gridfs_specs` test binaries, respectively.
                   export CRUD_TESTS_PATH="$(pwd)/../data/crud"
                   export CHANGE_STREAM_TESTS_PATH="$(pwd)/../data/change_stream"
+                  export ENCRYPTION_TESTS_PATH="$(pwd)/../data/client_side_encryption"
                   export GRIDFS_TESTS_PATH="$(pwd)/../data/gridfs"
                   export COMMAND_MONITORING_TESTS_PATH="$(pwd)/../data/command-monitoring"
                   export TRANSACTIONS_TESTS_PATH="$(pwd)/../data/transactions"
+
+                  # export environment variables for encryption tests (and redact them)
+                  set +o xtrace
+                  set +o errexit
+                  export MONGOCXX_TEST_AWS_SECRET_ACCESS_KEY="${cse_aws_secret_access_key}"
+                  export MONGOCXX_TEST_AWS_ACCESS_KEY_ID="${cse_aws_access_key_id}"
+                  set -o errexit
+                  set -o xtrace
+
                   if [ "Windows_NT" == "$OS" ]; then
                       CRUD_TESTS_PATH=$(cygpath -m $CRUD_TESTS_PATH)
                       CTEST_OUTPUT_ON_FAILURE=1 MSBuild.exe /p:Configuration=${build_type} RUN_TESTS.vcxproj
@@ -252,11 +268,24 @@ functions:
                           export MONGOCXX_ENABLE_SLOW_TESTS=1
                       fi
 
+                      # Spawn mongocryptd
+                      if [ ! -f '${workdir}'/mongodb_binaries_path.txt ]; then
+                          echo "ERROR: mongodb_binaries_path.txt not found, call start_mongod first"
+                          exit 1
+                      fi
+
+                      MONGODB_BINARIES=`cat ${workdir}/mongodb_binaries_path.txt`
+                      echo "$MONGODB_BINARIES"
+                      
+                      echo "starting mongocryptd"
+                      $MONGODB_BINARIES/mongocryptd -vvvv --logpath ./mongocryptd.logs --fork --pidfilepath="$(pwd)/mongocryptd.pid"
+                      
                       ulimit -c unlimited || true
                       # Run tests and examples 1-by-1 with "test_params" so we can run them with valgrind.
                       ${test_params} ./src/bsoncxx/test/test_bson
                       ${test_params} ./src/mongocxx/test/test_driver
                       ${test_params} ./src/mongocxx/test/test_change_stream_specs
+                      ${test_params} ./src/mongocxx/test/test_client_side_encryption_specs
                       ${test_params} ./src/mongocxx/test/test_crud_specs
                       ${test_params} ./src/mongocxx/test/test_gridfs_specs
                       ${test_params} ./src/mongocxx/test/test_command_monitoring_specs
